module.exports = {
  apps: [
    {
      name: "watcher",
      script: "./main_with_watcher.py",
      interpreter: "python3",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      env_file: ".env.prod",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/watcher-error.log",
      out_file: "./logs/watcher-out.log",
      time: true,
      env: {
        ENV: "prod",
        NODE_ENV: "production",
      },
    },
    {
      name: "watcher_image",
      script: "./main_with_watcher_mk_image.py",
      interpreter: "python3",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      env_file: ".env.prod",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/watcher-image-error.log",
      out_file: "./logs/watcher-image-out.log",
      time: true,
      env: {
        ENV: "prod",
        NODE_ENV: "production",
      },
    },
    {
      name: "watcher_image_rdr",
      script: "./main_with_watcher_mk_image_RDR.py",
      interpreter: "python3",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      env_file: ".env.prod",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/watcher-image-rdr-error.log",
      out_file: "./logs/watcher-image-rdr-out.log",
      time: true,
      env: {
        ENV: "prod",
        NODE_ENV: "production",
      },
    },
    {
      name: "kma_fetch",
      script: "/home/sbs/node_project/weather_server/kma_fetch/run_watcher_prod.sh",
      interpreter: "bash",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/kma-fetch-error.log",
      out_file: "./logs/kma-fetch-out.log",
      time: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "kma_fetch_rdr",
      script: "/home/sbs/node_project/weather_server/kma_fetch/run_watcher_prod_RDR.sh",
      interpreter: "bash",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/kma-fetch-rdr-error.log",
      out_file: "./logs/kma-fetch-rdr-out.log",
      time: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "weather_api",
      script: "/home/sbs/node_project/weather_server/server.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/weather_api_err.log",
      out_file: "./logs/weather_api_out.log",
      time: true,
      env: {
      MODE: "prod",
        ROOT_DIR_PROD: "/data/node_project/weather_data/out_data",
        ROOT_DIR_DEV: "D:/002.Code/002.node/weather_api/data/weather"

      },
    },
  ],
};
